spring.application.name=uptime-monitor
spring.config.import=optional:file:.env
spring.docker.compose.enabled=false

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:uptimeDB}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jwt
jwt.secret=${JWT_SECRET:this-is-a-local-dev-secret-key-minimum-32-chars}

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}